name: demo
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pandas
  - psycopg2
  - mysql-connector-python
  - prefect
  # - pip
  # - pip:
  #   - prefect[kubernetes]